<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Migration_Base
{
	private $name = 'tbl_users';

    public function up()
    {
		$columns = array(
				'id' => array(
						'type' => 'integer',
						'unsigned' => 1,
						'notnull' => 1,
						'default' => 0,
						'autoincrement' => true,
				),
				'username' => array(
						'type' => 'string',
						'notnull' => 1,
						'length' => 20
				),
				'password' => array(
						'type' => 'string',
						'notnull' => 1,
						'length' => 128
				),
				'email'		=> array(
						'type'	=> 'string',
						'notnull' => 1,
						'length'=> 128
				),
				'activkey'	=> array(
						'type'	=> 'string',
						'notnull' => 1,
						'length'=> 128
				),
				'createtime'	=> array(
						'type'	=> 'integer',
						'notnull' => 1,
						'default' => 0
				),

				'lastvisit'	=> array(
						'type'	=> 'integer',
						'notnull' => 1,
						'default' => 0
				),
			
				'superuser'	=> array(
						'type'	=> 'boolean',
						'notnull' => 1,
						'default'=> 0
				),
				'status'	=> array(
						'type'	=> 'integer',
						'notnull' => 1,
						'default'	=> 0
				),

		);
		$this->createTable( $this->name, $columns );	
    }

    public function down()
    {
		$this->dropTable( $this->name );
    }
}
