<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblProfilesFields extends Doctrine_Migration_Base
{
	private $name = 'tbl_profiles_fields';

    public function up()
    {
		$columns = array(
				'id' => array(
						'type' => 'integer',
						'unsigned' => 1,
						'notnull' => 1,
						'default' => 0,
						'autoincrement' => true,
				),

				'varname' => array(
						'type' => 'string',
						'notnull' => 1,
						'length' => 50
				),

				'title'		=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),

				'field_type'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 50
				),

				'field_size'=> array(
						'type'	=> 'integer',
						'notnull'	=> 1,
						'default'	=> 0
				),

				'field_size_min'=> array(
						'type'	=> 'integer',
						'notnull'	=> 1,
						'default'	=> 0
				),

				'required'=> array(
						'type'	=> 'boolean',
						'notnull'	=> 1,
						'default'	=> 0
				),

	  			'match'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),
			
	  			'range'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),
			
	  			'error_message'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),

	  			'other_validator'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),

	  			'defaults'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),
			
	  			'widget'=> array(
						'type'	=> 'string',
						'notnull'	=> 1,
						'length'	=> 255
				),
				
	  			'widgetparams'=> array(
						'type'	=> 'text',
						'notnull'	=> 1,
				),

				'position'=> array(
						'type'	=> 'integer',
						'notnull'	=> 1,
						'default'	=> 0
				),

				'visible'=> array(
						'type'	=> 'boolean',
						'notnull'	=> 1,
						'default'	=> 0,
						'length'	=> 1,
				)
		);

		$this->createTable( $this->name, $columns );
    }

    public function down()
    {
		$this->dropTable( $this->name );
    }
}
