<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpositionanddescriptioncolumnstojobstable extends Doctrine_Migration_Base
{
	private $name = 'tbl_jobs';

    public function up()
    {
		$this->addColumn($this->name, 'position', 'string', 255, array( 'notnull' => 1, 'default' => '' ) );
		$this->addColumn($this->name, 'description', 'text' );
    }

    public function down()
    {
		// TODO fix this for SQLite :/ (not supported yet!){
		$this->removeColumn( $this->name, 'position' );
		$this->removeColumn( $this->name, 'description' );
    }
}
